name: Deploy the static files to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Set Node.js version ${{ matrix.node-version }}"
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: "Install node"
      run: npm install -g yarn

    - name: "Install dependencies"
      run: |
        yarn

    - name: "Build the project"
      run: |
        yarn build

    - name: "Deploy to GitHub Pages on master branch"
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: master
